yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('follow/', views.follow_index, name='follow_index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='post_create'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('profile/<str:username>/', views.profile, name='profile'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import PublicationModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Заголовок', max_length=200)
    slug = models.SlugField('Адрес', unique=True)
    description = models.TextField('Описание')

    class Meta:
        verbose_name = 'Сообщество'
        verbose_name_plural = 'Сообщества'

    def __str__(self):
        return self.title


class Post(PublicationModel):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='group_name',
        verbose_name='Сообщество',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:15]

    def get_post_count(self):
        return Post.objects.filter(author=self.author).count()


class Comment(PublicationModel):
    text = models.TextField('Текст комментария')
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return f'{self.text[:15]} {self.pub_date:%d %b %H:%M}'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        related_name='follower',
        verbose_name='Пользователь',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        blank=True,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_follow'
            ),
            models.CheckConstraint(
                check=~models.Q(user=models.F('author')),
                name='user_not_author'
            ),
        ]

yatube/posts/forms.py
from django import forms

from posts.models import Post, Group, Comment


class PostForm(forms.ModelForm):
    group = forms.ModelChoiceField(
        queryset=Group.objects.all(),
        required=False,
        help_text='Группа, к которой будет относиться пост',
        label='Название группы',
    )

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {'text': 'Текст нового поста'}
        labels = {'text': 'Текст поста'}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', )
        help_texts = {'text': 'Текст нового комментария'}
        labels = {'text': 'Текст комментария'}

yatube/posts/views.py
import datetime

from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.conf import settings

from .models import Follow, Group, Post, Comment, User
from .forms import PostForm, CommentForm


def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.PAGINATOR_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/index.html'
    title = 'Последние обновления на сайте'
    context = {
        'page_obj': page_obj,
        'title': title,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    template = 'posts/group_list.html'
    post_list = group.group_name.all()
    paginator = Paginator(post_list, settings.PAGINATOR_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    author = User.objects.get(username=username)
    post_list = Post.objects.filter(author=author)
    paginator = Paginator(post_list, settings.PAGINATOR_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/profile.html'
    title = f'Профайл пользователя {username}'
    following = False
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user, author=author
        ).exists()
    context = {
        'author': author,
        'page_obj': page_obj,
        'title': title,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    comments = Comment.objects.filter(post=post)
    title = 'Пост ' + post.text[0:30]
    template = 'posts/post_detail.html'
    context = {
        'post': post,
        'title': title,
        'comments': comments,
        'form': form,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.pub_date = datetime.datetime.today()
        post.save()
        return redirect(f'/profile/{request.user.username}/')
    form = PostForm()
    template = 'posts/create_post.html'
    title = 'Новый пост'
    context = {
        'form': form,
        'title': title,
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect(f'/posts/{post_id}')
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect(f'/posts/{post_id}')
    template = 'posts/create_post.html'
    title = 'Редактировать пост'
    context = {
        'form': form,
        'title': title,
        'post': post,
        'is_edit': True,
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect(f'/posts/{post_id}/')


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, settings.PAGINATOR_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/follow.html'
    title = 'Моя лента'
    context = {
        'page_obj': page_obj,
        'title': title,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=request.user, author=author)
    if request.user != author and not is_follower.exists():
        Follow.objects.create(user=request.user, author=author)
    return redirect(f'/profile/{author.username}/')


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    is_follower = Follow.objects.filter(user=request.user, author=author)
    if is_follower.exists():
        is_follower.delete()
    return redirect(f'/profile/{author.username}/')

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">{{ title }}</div>
        <div class="card-body">
          {% include 'includes/check_form_errors.html' %}
          <form method="post" enctype="multipart/form-data"
            {% if is_edit %}
              action="{% url 'posts:post_edit' post.id %}"
            {% else %} 
              action="{% url 'posts:post_create' %}"
            {% endif %}
          >
            {% csrf_token %}
            {% load user_filters %}
            {% include 'includes/draw_form.html' %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}   
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
</div>
{% endblock %} 

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
  <div class="container py-5">
    {% include 'includes/switcher.html' %}
    <h1>{{ title }}</h1>
    {% cache 20 index_page with page_obj %}
    {% for post in page_obj %}
      {% include 'includes/post_list.html' %}
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% endcache %}
    {% include 'includes/paginator.html' %}
  </div> 
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ group.title }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
      {% include 'includes/post_list.html' %}
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
  <div class="container py-5">
    {% include 'includes/switcher.html' %}
    <h1>{{ title }}</h1>
    {% cache 20 index_page with page_obj %}
    {% for post in page_obj %}
      {% include 'includes/post_list.html' %}
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% endcache %}
    {% include 'includes/paginator.html' %}
  </div> 
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group.title }}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}
          <li class="list-group-item">
            Автор: 
            {% if post.author.get_full_name %}
              {{ post.author.get_full_name }}
            {% else %}
              {{ post.author.username }}
            {% endif %}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post.get_post_count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
       {{ post.text }}
      </p>
      {% if user.is_authenticated and user == post.author %}     
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          редактировать запись
        </a> 
    {% endif %}
    {% if user.is_authenticated %}
    <div class="card my-4">
      <h5 class="card-header">Добавить комментарий:</h5>
      <div class="card-body">
        <form method="post" action="{% url 'posts:add_comment' post.id %}">
          {% csrf_token %}      
          <div class="form-group mb-2">
            {{ form.text|addclass:"form-control" }}
          </div>
          <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
      </div>
    </div>
  {% endif %}
  {% for comment in comments %}
    <div class="media mb-4">
      <div class="media-body">
        <h5 class="mt-0">
          <a href="{% url 'posts:profile' comment.author.username %}">
            {{ comment.author.username }}
          </a>
        </h5>
          <p>
           {{ comment.text }}
          </p>
        </div>
      </div>
    {% endfor %}
    </article>
  </div>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="mb-5">
    <h1>Все посты пользователя 
      {% if author.get_full_name %}
        {{ author.get_full_name }}
      {% else %}
        {{ author.username }}
      {% endif %}        
      </h1>
    <h3>Всего постов: {{page_obj.paginator.object_list.count }}</h3>
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
     {% endif %}
  </div>
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }} 
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
  </article> 
  {% if post.group %}     
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}   
  {% include 'includes/paginator.html' %}
</div>
{% endblock %}